### PR TITLE
added support for default action parameters

### PR DESCRIPTION
**Pull request by ddragosd**
This is still WIP , I'd like to add integration tests but I didn't quite figure it out how to execute them locally.

### CODE REVIEW

**Comment by pritidesai** [comment]
How about "npm test" from home dir "~/openwhisk-client-js/"?

This link has lot of details:
https://travis-ci.org/openwhisk/openwhisk-client-js/jobs/199010764

Cheers
Priti

**Comment by jthomas** [comment]
@ddragosd Did you see this README? https://github.com/openwhisk/openwhisk-client-js/tree/master/test/integration 

Is there something else missing? Running `npm run-script test-integration` should run the suite once the env vars are set up or you can install `ava` locally and just run the single file.

**Comment by ddragosd** [comment]
thanks @jthomas . I'll start a local OW instance to run the integration tests and add them to the PR. We may also have to add `ignore_certs:true` when configuring the JS client.
 
In a separate PR we could maybe also automate the execution of these tests including the setup with the actions/triggers.

**Comment by jthomas** [comment]
I'm closing this as I manually merged the code into a recent release.

**Pull request closed without merging**
