### PR TITLE
Fix path for routemgmt package.

### PR DESCRIPTION
**Pull request by rabbah**
The pr updates the path to the routemgmt package for https://github.com/openwhisk/openwhisk/commit/4550ac1316d4e1690b7d5e461c26977d7abca34a.

### CODE REVIEW

**Comment by jthomas** [comment]
Thanks for letting me know.
Can you fix the unit tests and check the integration test for that operation still works?

**Comment by rabbah** [comment]
Will do.

**Comment by rabbah** [comment]
how do i run the unit tests locally?

**Comment by rabbah** [comment]
never mind the last q.

**Comment by rabbah** [comment]
I followed the instructions to run the integration tests - but they stop after creating the required test artifacts. What do I do next?

**Comment by jthomas** [comment]
Oh dear. I'm away until next week on vacation. 
Will look at this on my return!

**Comment by rabbah** [comment]
@jthomas are any of the integration tests dealing with api routes?

**Comment by csantanapr** [comment]
going to merge this but I was not able to run the integration tests locally, from master.
It fails in simple test cases such as, this is setting the env  vars correctly.
I have a package `demo` and the namespace contains `/demo`

here is an example

```
  4. actions › list all actions using options namespace

  t.is(action.namespace, NAMESPACE)
              |          |
              |          "csantana@example.com_demo"
              "csantana@example..com_demo/demo"

      actions.test.js:47:9
    actions.test.js:46:12

```

**Pull request merged**
